spring:
  profiles:
    active: local

---
spring:
  profiles: local

#  jpa:
#    generate-ddl: true
#    show_sql: true
#    format_sql: true
#    use_sql_comments: true

  jwt.secret: wjsurshdmf@$&

#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: debug
server:
  port: 9091

#actuator
#https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
#      show-details: always


# 운영 환경
---
spring:
  profiles:
    group:
      set1: real-db

server:
  port: 9091


---
spring:
  profiles:
    group:
      set2: real-db

server:
  port: 9092

#스프링2.4부터 include가 사용이 안된다.권고같은게 아니라 아에 컴파일이 안됨. 영어라고 쫄지말고 천천히 읽어보자 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide