spring:
  profiles:
    active: local

---
spring:
  profiles: local

#  jpa:
#    generate-ddl: true
#    show_sql: true
#    format_sql: true
#    use_sql_comments: true

  jwt.secret: wjsurshdmf@$&

#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: debug
server:
  port: 9091

#actuator
#https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
#      show-details: always


# 운영 환경
---
spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 9091


---
spring.profiles: set2
spring.profiles.include: real-db

server:
  port: 9092