spring:
  profiles:
    active: "local"


---
spring:
  config:
    activate:
      on-profile: "local"
#  jpa:
#    generate-ddl: true
#    show_sql: true
#    format_sql: true
#    use_sql_comments: true

  jwt.secret: wjsurshdmf@$&

#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: debug


#actuator
#https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
#      show-details: always


---
spring:
  profiles:
    group:
      set1: "live,realdb"
      set2: "live,realdb"


# 운영 환경
---
spring:
  config:
    activate:
      on-profile: "set1"



---
spring:
  config:
    activate:
      on-profile: "set2"



#스프링2.4부터 include가 사용이 안된다.권고같은게 아니라 아에 컴파일이 안됨. 영어라고 쫄지말고 천천히 읽어보자 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide