spring:
  profiles:
    active: "local"

---
spring:
  profiles:
    group:
      "local": "testenv,testdb,globalconstant"
---
spring:
  config:
    activate:
      on-profile: "local"


---
spring:
  config:
    activate:
      on-profile: "testenv"

  jwt.secret: wjsurshdmf@$&

  #actuator
  #https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html
  management:
    endpoints:
      enabled-by-default: false
    endpoint:
      health:
        enabled: true
  #      show-details: always

  #logging:
  #  level:
  #    root: warn
  #    org.hibernate.SQL: debug

  #  jackson:
  #    serialization:
  #      fail-on-empty-beans : false

  #  jpa:
#    generate-ddl: true
#    show_sql: true
#    format_sql: true
#    use_sql_comments: true
---
spring:
  config:
    activate:
      on-profile: "testdb"


  datasource:
    url: jdbc:h2:tcp://localhost/~/advance_multi_module_lab
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: "globalconstant"


---



#스프링2.4부터 include가 사용이 안된다.권고같은게 아니라 아에 컴파일이 안됨. 영어라고 쫄지말고 천천히 읽어보자 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-Config-Data-Migration-Guide